# Generated by Django 4.0.2 on 2023-04-06 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Compte',
            },
        ),
        migrations.CreateModel(
            name='Dynef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
            options={
                'db_table': 'Dynef',
            },
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siret', models.CharField(max_length=14, unique=True)),
                ('raison_sociale', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Societe',
            },
        ),
        migrations.CreateModel(
            name='TotalEnergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
            options={
                'db_table': 'TotalEnergie',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueCalcule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_today', models.DateField()),
                ('resultat', models.FloatField()),
                ('dynef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.dynef')),
                ('total_energie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.totalenergie')),
            ],
            options={
                'db_table': 'HistoriqueCalcule',
            },
        ),
        migrations.CreateModel(
            name='Compteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_compteur', models.CharField(max_length=100)),
                ('typeEnergie', models.CharField(choices=[('D', 'Dynef'), ('T', 'TotalEnergie')], max_length=1)),
                ('consommation', models.FloatField()),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.societe')),
            ],
            options={
                'db_table': 'Compteur',
            },
        ),
    ]
